services:
  Smp25:
    build:
      context: .
      dockerfile: Dockerfile
    image: smp25-frontend:latest
    container_name: Smp25-Frontend
    restart: unless-stopped
    ports:
      - "8080:80" # Puerto local:contenedor
    networks:
      - smp25-network
    labels:
      - "com.smp25.version=2.50.4"
      - "com.smp25.service=frontend"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  smp25-network:
    driver: bridge
