services:
  Delison-Frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: delison-frontend:latest
    container_name: delison-frontend
    restart: unless-stopped
    ports:
      - "7080:80" # Puerto local:contenedor
    networks:
      - delison-frontend-network
    labels:
      - "com.delison.version=2.50.4"
      - "com.delison.service=frontend"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  delison-frontend-network:
    driver: bridge
