// <auto-generated />
using System;
using MicroServicioTracking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroServicioTracking.Migrations
{
    [DbContext(typeof(DbTrackingContext))]
    [Migration("20250226023750_AddPayrollAndPayrollEmployeesTables")]
    partial class AddPayrollAndPayrollEmployeesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroServicioTracking.Models.AccountBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("EAplicaFiscal")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("eAplicaFiscal");

                    b.Property<string>("FolioCheque")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("folioCheque");

                    b.Property<string>("FolioSinCheque")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("folioSinCheque");

                    b.Property<int>("IdBanco")
                        .HasColumnType("int")
                        .HasColumnName("id_banco");

                    b.Property<int>("IdBussines")
                        .HasColumnType("int")
                        .HasColumnName("id_Bussines");

                    b.Property<string>("Interbancaria")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .HasColumnName("Interbancaria");

                    b.Property<string>("NameAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nameaccount");

                    b.Property<string>("NumberAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numberaccount");

                    b.Property<string>("SignAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("signaccount");

                    b.HasKey("Id");

                    b.ToTable("accountbanks");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("branch");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(145)
                        .HasColumnType("nvarchar(145)")
                        .HasColumnName("contact");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.Property<string>("NumBranch")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("numbranch");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("picture");

                    b.HasKey("Id");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.BillingManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Consecutive")
                        .HasColumnType("int")
                        .HasColumnName("consecutive");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateEnd");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateStart");

                    b.Property<string>("EfirmaPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("efirma_pass");

                    b.Property<int>("FiscalRegime")
                        .HasColumnType("int")
                        .HasColumnName("fiscal_regime");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int")
                        .HasColumnName("fiscal_year");

                    b.Property<decimal>("II3")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("i_i3");

                    b.Property<decimal>("IIeps")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("i_ieps");

                    b.Property<decimal>("IIva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("i_iva");

                    b.Property<int>("IdRoot")
                        .HasColumnType("int")
                        .HasColumnName("id_root");

                    b.Property<string>("PathCer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_cer");

                    b.Property<string>("PathKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("path_key");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prefix");

                    b.Property<decimal>("RIeps")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("r_ieps");

                    b.Property<decimal>("RIva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("r_iva");

                    b.HasKey("Id");

                    b.ToTable("billingmanagement");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.CashRegisters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdStore")
                        .HasColumnType("int")
                        .HasColumnName("id_store");

                    b.HasKey("Id");

                    b.ToTable("cashregisters");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.ConceptsxIncorExp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("description");

                    b.Property<int?>("IdIncorExp")
                        .HasColumnType("int")
                        .HasColumnName("id_incorexp");

                    b.Property<bool>("Iva")
                        .HasColumnType("bit")
                        .HasColumnName("iva");

                    b.Property<decimal>("Iva2")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("iva2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("conceptsxincorexp");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.ConceptsxLoansCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("IdLoanAndCredit")
                        .HasColumnType("int")
                        .HasColumnName("id_loanandcredit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("conceptsxloanscredits");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Creditxcustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DateP")
                        .HasColumnType("datetime2")
                        .HasColumnName("datep");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<string>("NumberNote")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numbernote");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.ToTable("creditsxcustomers");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Company")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Cuenta")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("Cuenta");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("IdBranch")
                        .HasColumnType("int")
                        .HasColumnName("id_branch");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NameContact")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("namecontact");

                    b.Property<int?>("NumCliente")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool?>("Vigente")
                        .HasColumnType("bit")
                        .HasColumnName("vigente");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short?>("BaseHours")
                        .HasColumnType("smallint")
                        .HasColumnName("basehours");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClockPassword")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("clock_password");

                    b.Property<string>("Cp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("employee_code");

                    b.Property<int?>("IdBank")
                        .HasColumnType("int")
                        .HasColumnName("id_bank");

                    b.Property<int?>("IdBranch")
                        .HasColumnType("int")
                        .HasColumnName("id_branch");

                    b.Property<DateTime?>("IngressDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ingressdate");

                    b.Property<decimal?>("Loan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("loan");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Picture")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("position");

                    b.Property<decimal?>("PriceXHour")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pricexhour");

                    b.Property<string>("Rfc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Saving")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saving");

                    b.Property<string>("State")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.Property<bool?>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.EmployeesxLoans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Comments")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("comments");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("id_employee");

                    b.Property<int?>("IdPadre")
                        .HasColumnType("int")
                        .HasColumnName("id_padre");

                    b.Property<decimal>("Loan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("loan");

                    b.Property<decimal>("Payment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("payment");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("employeesxloans");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.FiscalRegime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("fiscalregime");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.HRManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Consecutive")
                        .HasColumnType("int")
                        .HasColumnName("consecutive");

                    b.Property<int>("IdBranch")
                        .HasColumnType("int")
                        .HasColumnName("id_branch");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prefix");

                    b.Property<int>("Vigency")
                        .HasColumnType("int")
                        .HasColumnName("vigency");

                    b.HasKey("Id");

                    b.ToTable("setuphr");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Incomeandexpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStamped")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("id_account");

                    b.Property<int?>("IdBusinnes")
                        .HasColumnType("int")
                        .HasColumnName("id_businnes");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<int?>("IdExpend")
                        .HasColumnType("int")
                        .HasColumnName("id_expend");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumberDocument")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PaymentMonth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_month");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Uuid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("incomeandexpense");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.InformationAditional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("FolioFiscal")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("foliofiscal");

                    b.Property<int?>("IdConditionspay")
                        .HasColumnType("int")
                        .HasColumnName("id_conditionspay");

                    b.Property<int?>("IdIncorexp")
                        .HasColumnType("int")
                        .HasColumnName("id_incorexp");

                    b.Property<int?>("IdTypemoney")
                        .HasColumnType("int")
                        .HasColumnName("id_typemoney");

                    b.Property<int?>("IdTypepay")
                        .HasColumnType("int")
                        .HasColumnName("id_typepay");

                    b.Property<string>("NumberEntry")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numberentry");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("ordernumber");

                    b.Property<string>("PurchaseOrder")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("purchaseorder");

                    b.Property<string>("Quote")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("quote");

                    b.HasKey("Id");

                    b.ToTable("informationaditional");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Loanandcredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Payments")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("payments");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("loansandcredits");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.PayrollEmployee", b =>
                {
                    b.Property<int>("PayrollEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollEmployeeId"));

                    b.Property<decimal>("AccreditedEmploymentSubsidy")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Article114Subsidy")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Article96Tax")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ChildSupport")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("DailySalary")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("EmploymentSubsidy")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("HousingFundWithholding")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IntegratedDailySalary")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MedicalInsurance")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("OtherIncome")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("PayrollId")
                        .HasColumnType("int");

                    b.Property<decimal>("RetirementInsurance")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SocialSecurity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TaxableEarnings")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TotalArticle115EmploymentSubsidy")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Wages")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("WorkedDays")
                        .HasColumnType("int");

                    b.HasKey("PayrollEmployeeId");

                    b.HasIndex("Name");

                    b.HasIndex("PayrollId");

                    b.ToTable("PayrollEmployees");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.PayrollRecord", b =>
                {
                    b.Property<int>("PayrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollId"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PayrollId");

                    b.ToTable("PayrollRecords");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.PosSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("Consecutive")
                        .HasColumnType("int")
                        .HasColumnName("consecutive");

                    b.Property<int>("IdBranch")
                        .HasColumnType("int")
                        .HasColumnName("id_branch");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<int?>("IdDocumentType")
                        .HasColumnType("int")
                        .HasColumnName("id_document_type");

                    b.Property<string>("Prefix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prefix");

                    b.Property<bool?>("PrintScreen")
                        .HasColumnType("bit")
                        .HasColumnName("printscreen");

                    b.Property<bool?>("SalesExistence")
                        .HasColumnType("bit")
                        .HasColumnName("salesexistence");

                    b.HasKey("Id");

                    b.ToTable("setupadministration");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Salesxconcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int?>("BoxNumber")
                        .HasColumnType("int")
                        .HasColumnName("boxnumber");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    b.Property<int?>("IdSale")
                        .HasColumnType("int")
                        .HasColumnName("id_sale");

                    b.Property<decimal?>("Pu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pu");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<bool?>("Unit")
                        .HasColumnType("bit")
                        .HasColumnName("unit");

                    b.Property<int?>("UnitNumber")
                        .HasColumnType("int")
                        .HasColumnName("unitnumber");

                    b.HasKey("Id");

                    b.HasIndex("IdSale");

                    b.ToTable("salesxconcept");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Salesxcustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18)")
                        .HasColumnName("amount");

                    b.Property<bool?>("Credit")
                        .HasColumnType("bit")
                        .HasColumnName("credit");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("id_customer");

                    b.Property<bool?>("Lector")
                        .HasColumnType("bit")
                        .HasColumnName("lector");

                    b.Property<string>("NumberNote")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numbernote");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.ToTable("salesxcustomer");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.SetupManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("AdministratorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("administratorname");

                    b.Property<string>("AdministratorTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("administratortitle");

                    b.Property<int>("ConsecutiveCreditNote")
                        .HasColumnType("int")
                        .HasColumnName("consecutive_credit_note");

                    b.Property<int>("ConsecutiveReceipt")
                        .HasColumnType("int")
                        .HasColumnName("consecutive_receipt");

                    b.Property<string>("DirectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("directorname");

                    b.Property<string>("DirectorTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("directortitle");

                    b.Property<string>("GerencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gerencyname");

                    b.Property<string>("GerencyTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gerencytitle");

                    b.Property<int>("IdRoot")
                        .HasColumnType("int")
                        .HasColumnName("id_root");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("iva");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("operatorname");

                    b.Property<string>("OperatorTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("operatortitle");

                    b.HasKey("Id");

                    b.ToTable("setupmanagement");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Stores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Cp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cp");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdBranch")
                        .HasColumnType("int")
                        .HasColumnName("id_branch");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("stores");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Tracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("company");

                    b.Property<DateTime?>("Datet")
                        .HasColumnType("datetime")
                        .HasColumnName("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("Origin")
                        .HasColumnType("nchar(50)")
                        .HasColumnName("origin");

                    b.Property<string>("User")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.ToTable("trackings");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.ZipCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asentamientos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("asentamiento");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Cp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cp");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.HasKey("Id");

                    b.ToTable("zipcodes");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.expensecategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountingCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<byte?>("ApprovalLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DeductiblePercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("IdBusinnes")
                        .HasColumnType("int")
                        .HasColumnName("id_businnes");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<bool?>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequiresVoucher")
                        .HasColumnType("bit");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("expensecategories");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Creditxcustomer", b =>
                {
                    b.HasOne("MicroServicioTracking.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IdCustomer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.PayrollEmployee", b =>
                {
                    b.HasOne("MicroServicioTracking.Models.PayrollRecord", "PayrollRecord")
                        .WithMany("PayrollEmployees")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollRecord");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Salesxconcept", b =>
                {
                    b.HasOne("MicroServicioTracking.Models.Salesxcustomer", "Sale")
                        .WithMany()
                        .HasForeignKey("IdSale");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.Salesxcustomer", b =>
                {
                    b.HasOne("MicroServicioTracking.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IdCustomer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.expensecategory", b =>
                {
                    b.HasOne("MicroServicioTracking.Models.expensecategory", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("MicroServicioTracking.Models.PayrollRecord", b =>
                {
                    b.Navigation("PayrollEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
