name: Deploy
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production
      run: |
        # Crear y configurar clave SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Ejecutar deploy
        ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/deploy_key \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            'bash -l /bi/repos/Smp25/deploy.sh'
        
        # Limpiar
        rm ~/.ssh/deploy_key
